# Generated by Django 3.1.7 on 2021-08-05 12:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0006_album_public'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('album_mark', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='albummark',
            unique_together={('album', 'author')},
        ),
    ]
