# Generated by Django 3.1.7 on 2021-04-05 19:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('albums', '0003_auto_20210405_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='owners',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
