# Generated by Django 3.1.7 on 2021-08-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0005_auto_20210604_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
