# Generated by Django 3.1.7 on 2021-12-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0006_album_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='image_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
