# Generated by Django 3.1.7 on 2021-04-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.CharField(choices=[('Pop', 'Pop'), ('Rock', 'Rock'), ('Other', 'Other')], default='Other', max_length=20),
        ),
        migrations.AddField(
            model_name='song',
            name='performer',
            field=models.CharField(default='Unknown', max_length=120),
        ),
    ]
