# Generated by Django 3.1.7 on 2021-05-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0004_remove_song_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, default=2000, null=True),
        ),
    ]
