# Generated by Django 3.1.7 on 2021-12-27 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0006_remove_song_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
