# Generated by Django 3.1.7 on 2021-05-29 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song_mark', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songmark',
            name='create_date',
        ),
    ]
