# Generated by Django 3.1.7 on 2021-08-05 12:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('song', '0005_song_year'),
        ('song_mark', '0003_auto_20210616_2155'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='songmark',
            unique_together={('song', 'author')},
        ),
    ]
