# Generated by Django 3.1.7 on 2021-07-18 15:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0005_song_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('favourite_song', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favouritesong',
            unique_together={('song', 'author')},
        ),
    ]
