# Generated by Django 3.1.7 on 2021-05-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_comment', '0002_auto_20210530_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songcomment',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
