# Generated by Django 3.1.7 on 2021-06-16 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0005_song_year'),
        ('song_comment', '0003_auto_20210530_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songcomment',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='song.song'),
        ),
    ]
