# Generated by Django 3.1.5 on 2021-06-04 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_album_owners'),
        ('album_comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumcomment',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='albums.album'),
        ),
        migrations.AlterField(
            model_name='albumcomment',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
